#!/bin/sh
SPY_DIR=$(dirname -- "$0")
case "$1" in
	init)
		if [ -f ".env.py" ]; then
			echo "The directory is already initiated with spy"
		else
			cp "$SPY_DIR/bootstrap/.spy.$2" ".spy.$2"
		fi
		;;
	module)
		cd "$SPY_DIR"
		vim "$SPY_DIR/run.py"
		;;
	*)
		python3 $SPY_DIR/run.py $@
		;;
esac
